#!/bin/bash
# SweatBet Testing Checklist
# Save this and run through each step

echo "🧪 SweatBet Testing Checklist"
echo "=============================="
echo ""
echo "📍 PRODUCTION URL: https://sweatbet-sigma.vercel.app/?betId=1"
echo ""
echo "Phase 1: UI & Connection ✅"
echo "□ App loads with purple-pink gradient"
echo "□ MetaMask connection prompt appears"
echo "□ Wallet connects successfully"
echo "□ Challenge details display correctly"
echo "□ 'BET 1 USDC' button is visible"
echo ""
echo "Phase 2: Betting Flow ⚠️"
echo "□ Click 'BET 1 USDC' button"
echo "□ USDC approval transaction appears"
echo "□ Approve USDC spend"
echo "□ Place bet transaction appears"
echo "□ Confirm bet transaction"
echo "□ Button changes to 'PROVE WORKOUT'"
echo "□ System message: 'Bet placed successfully'"
echo ""
echo "Phase 3: Strava Proof (Needs Client Secret) ⚠️"
echo "□ Click 'PROVE WORKOUT' button"
echo "□ Redirects to Strava OAuth"
echo "□ Login to Strava"
echo "□ Authorize SweatBet"
echo "□ Redirects back to app"
echo "□ Shows list of qualifying activities"
echo "□ Select a 5km+ activity"
echo "□ Proof generation starts"
echo "□ Proof submitted to contract"
echo "□ Success message appears"
echo ""
echo "Known Issues:"
echo "⚠️ Strava OAuth will fail without NEXT_PUBLIC_STRAVA_CLIENT_SECRET"
echo "⚠️ VLayer proof generation needs testing"
echo "⚠️ XMTP messaging is UI-only (no real chat yet)"
echo ""
